//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wardrobe.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ClothingDetail
    {
        //Main db with foreign keys included
        [Display(Name = "Clothing Details")]
        public int ClothingID { get; set; }
        public string Title { get; set; }
        public string Color { get; set; }
        public string Photo { get; set; }
        [Display(Name ="Occassion")]
        public int OccassionID { get; set; }
        [Display(Name = "Season")]
        public int SeasonID { get; set; }
        [Display(Name = "Clothing Type")]
        public int TypeID { get; set; }

        //Foreign keys for the db
        public virtual ClothingType ClothingType { get; set; }
        public virtual Occassion Occassion { get; set; }
        public virtual Season Season { get; set; }
    }
}
