//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wardrobe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClothingDetail
    {
        public int ClothingID { get; set; }
        public string Title { get; set; }
        public string Color { get; set; }
        public string Photo { get; set; }
        public int OccassionID { get; set; }
        public int SeasonID { get; set; }
        public int TypeID { get; set; }
    }
}
